apiVersion: v1
kind: Pod
metadata:
  name: any-metric-pod
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8080'
spec:
  containers:
    - name: any-metric-container
      image: ghcr.io/luizfnunesmarques/any-metric:latest
      command: ["any-metric"]
      args:
        - "--metric=gauge_metric:5s:1.0:gauge"
        - "--metric=counter_metric:10s:5.0:counter"
      ports:
        - containerPort: 8080
